name: CI

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: |
        cd ui
        npm install
      
    - name: Build
      run: |
        cd ui
        npm run build
    
    - name: Lint
      run: |
        cd ui
        npm run lint:ci