name: Github Pages

on:
  push:
    branches: [ "main", "DEV-shift-to-ts" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Build Vite app
        run: |
          cd ui
          npm install
          npm run build

      - name: Copy wheels to dist
        run: |
          cp ui/public/*.whl ui/dist/assets/
          cp ui/public/coi-serviceworker.js ui/dist/assets/
          cp ui/public/z3* ui/dist/assets/
          
      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ui/dist
          branch: gh-pages
          clean: true
