name: Github Pages

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Build Vite app
        run: |
          cd vite-app
          npm install
          npm run build

      - name: Copy wheels to dist
        run: |
          cp vite-app/public/*.whl vite-app/dist/assets/
          cp vite-app/public/coi-serviceworker.js vite-app/dist/assets/
          cp vite-app/public/z3* vite-app/dist/assets/
          
      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: vite-app/dist
          branch: gh-pages
          clean: true
